announce = false

description = 'test'
website = 'test.com'
gamemode = 'Freeroam'

language = 'en'
modules = [ 'js-module' ]
name = 'TestServer'
players = 2
port = 7788
tags = [ 'customTag1', 'customTag2', 'customTag3', 'customTag4' ]

resources = [ 
    'core',
    'web'
]

# Turn this off in production mode
debug = true

# Leave host as 0.0.0.0, don't change it.
host = '0.0.0.0'

[voice]
streamingTickRate = 10
bitrate = 64000
externalHost = "127.0.0.1"
externalPort = 7798
externalPublicPort = 7799
externalSecret = 4240677748
